version: 3

services:
  web:
    container_name: all-the-music
    restart: always
    build: .
    ports: 3000
    links: mongo
  
  mongo:
    container_name: mongodb
    image: mongo
    ports: 27017